
title: 钱包订单
type: kk/micro

services:
  Order:
    title: 订单服务
    tasks:
      Recharge:
        title: 充值
        name: /order/recharge
        input:
          - name: walletId
            type: long
            title: 钱包ID
          - name: value
            type: long
            title: 充值金额(分)
          - name: freeze
            type: boolean
            title: 是否冻结
          - name: title
            type: string
            title: 标题
          - name: options
            type: object
            title: 其他数据
        output:
          - name: order
            title: 订单
            omitempty: true
            type: Order
      Revoke:
        title: 提现
        name: /order/revoke
        input:
          - name: walletId
            type: long
            title: 钱包ID
          - name: value
            type: long
            title: 提现金额(分)
          - name: freeze
            type: boolean
            title: 是否冻结
          - name: title
            type: string
            title: 标题
          - name: options
            type: object
            title: 其他数据
        output:
          - name: order
            title: 订单
            omitempty: true
            type: Order
      Cancel:
        title: 取消
        name: /order/cancel
        input:
          - name: id
            type: long
            title: 订单ID
        output:
          - name: order
            title: 订单
            omitempty: true
            type: Order
      Execute:
        title: 执行
        name: /order/execute
        input:
          - name: id
            type: long
            title: 订单ID
        output:
          - name: order
            title: 订单
            omitempty: true
            type: Order
      Query:
        title: 查询订单
        name: /order/query
        type: query
        input:
          - name: id
            title: 订单ID
            type: object
          - name: orderBy
            type: string
            title: desc 降序默认 asc 升序
          - name: type
            type: string
            title: 类型 多个逗号分割
          - name: status
            type: string
            title: 状态 多个逗号分割
          - name: startTime
            type: object
            title: 开始时间(秒)
          - name: endTime
            type: object
            title: 开始时间(秒)
        output:
          - name: items
            title: 流水
            omitempty: true
            type: Order[]
      Get:
        title: 获取订单
        name: /order/get
        input:
          - name: id
            title: 订单ID
            type: object
        output:
          - name: order
            title: 流水
            omitempty: true
            type: Order
      


objects:
  Order:
    title: 订单
    name: order
    type: db
    fields:
      - name: title
        type: string
        title: 标题
        length: 255
      - name: items
        type: object
        title: 交易明细
      - name: options
        type: object
        title: 其他数据
      - name: type
        type: int
        title: 类型
        index: asc
      - name: status
        type: int
        title: 状态
        index: asc
      - name: ctime
        type: long
        title: 创建时间
        index: asc

      