
title: 钱包
type: kk/micro

services:
  Wallet:
    title: 钱包服务
    tasks:
      WalletCreate:
        title: 创建钱包
        name: wallet/create
        output:
          - name: wallet
            title: 钱包
            omitempty: true
            type: Wallet
      WalletGet:
        title: 获取钱包
        name: wallet/get
        input:
          - name: id
            title: 钱包ID
            type: long
        output:
          - name: wallet
            title: 钱包
            omitempty: true
            type: Wallet
      ItemQuery:
        title: 查询流水
        name: item/query
        type: query
        input:
          - name: id
            title: 钱包ID
            type: long
          - name: orderId
            type: object
            title: 订单ID
          - name: orderBy
            type: string
            title: desc 降序默认 asc 升序
          - name: startTime
            type: object
            title: 开始时间(秒)
          - name: endTime
            type: object
            title: 开始时间(秒)
        output:
          - name: items
            title: 流水
            omitempty: true
            type: Item[]
  Order:
    title: 订单服务
    tasks:
      Recharge:
        title: 充值
        name: order/recharge
        input:
          - name: walletId
            type: long
            title: 钱包ID
          - name: value
            type: long
            title: 交易金额(分)
        output:
          - name: order
            title: 订单
            omitempty: true
            type: Order
      Revoke:
        title: 提现
        name: order/revoke
        input:
          - name: walletId
            type: long
            title: 钱包ID
          - name: value
            type: long
            title: 交易金额(分)
        output:
          - name: order
            title: 订单
            omitempty: true
            type: Order
      Transfer:
        title: 转账
        name: order/transfer
        input:
          - name: fwalletId
            type: long
            title: 付款钱包ID
          - name: twalletId
            type: long
            title: 收款钱包ID
          - name: value
            type: long
            title: 交易金额(分)
        output:
          - name: order
            title: 订单
            omitempty: true
            type: Order
      OrderGet:
        title: 获取订单
        name: order/get
        input:
          - name: id
            type: long
            title: 订单ID
        output:
          - name: order
            title: 订单
            omitempty: true
            type: Order

objects:
  Wallet:
    title: 钱包
    name: wallet
    type: db
    fields:
      - name: value
        type: long
        title: 余额(分)
      - name: inValue
        type: long
        title: 累计收入(分)
      - name: outValue
        type: long
        title: 累计支出(分)
      - name: iid
        type: long
        title: 最后流水号
      - name: ctime
        type: long
        title: 创建时间
      - name: mtime
        type: long
        title: 修改时间
  Item:
    title: 交易流水
    name: item
    type: db
    fields:
      - name: iid
        type: long
        title: 流水号
        index: asc
      - name: walletId
        type: long
        title: 钱包ID
        index: asc
      - name: orderId
        type: long
        title: 订单ID
        index: asc
      - name: walletValue
        type: long
        title: 变更后余额(分)
      - name: value
        type: long
        title: 增加的余额(分)
      - name: ctime
        type: long
        title: 创建时间
        index: desc

  Order:
    title: 订单
    name: order
    type: db
    fields:
      - name: fitemId
        type: long
        title: 支出流水ID
      - name: titemId
        type: long
        title: 收入流水ID
      - name: fwalletId
        type: long
        title: 支出钱包ID
      - name: twalletId
        type: long
        title: 收入钱包ID
      - name: value
        type: long
        title: 交易金额(分)
      - name: ctime
        type: long
        title: 创建时间

      